### ISSUE TITLE
[WIP] add strimzi-kafka-cluster-operator

### ISSUE THREAD

**Issue by Spedoske** [xlab-uiuc/acto#230]
This continued issue is from pull request #229

`strimzi-kafka-cluster-operator` is an operator write by Java. Therefore, the source code information is not available to Acto.
- [ ] add `README.md`
- [x] add `k8s_mapping.py`
- [ ] add `prune_blackbox.py` if needed
- [x] lock image versions
- [x] perform a full Acto run

I decide to implement the schema by a monkey patch, because I do not want to pollute the codebase by adding language specific classes.

The current progress of the branch:

1. Acto can detect the resource schema.
2. Acto can apply the schema to the input model
3. Acto can generate test cases for Quantity schema

See https://github.com/xlab-uiuc/acto/pull/229#issuecomment-1616137612

**Comment by tianyin** [comment]
Close this issue as @Spedoske is no longer working on it. 

@MarkintoshZ will take it over and #274 is created.
