### ISSUE TITLE
SOSP-AE TODOs

### ISSUE THREAD

**Issue by tianyin** [xlab-uiuc/acto#255]
- [x] The CloudLab profile automation @whentojump 
    - Previously #257 
    - Now https://github.com/xlab-uiuc/acto-cloudlab and done
- [x]  #256 More detailed docs for running all the test campaigns (improving https://github.com/xlab-uiuc/acto/blob/sosp-ae/test_campaign.md) @whentojump 
- [x] Move data to submodule @tylergu 
    - [x] Now the tests are failing due to `No space left on device` (https://github.com/xlab-uiuc/acto/actions/runs/5696312801/job/15441163609)
- [x] Unexpected CloudLab page @whentojump @tylergu  
    - [x] https://uiuc-sysnet.slack.com/archives/C05ARSTLC6R/p1690578794441579
- [x] Proofread @marshtompsxd 
- [x] Proofread @tylergu 
- [x] @tylergu walk through the steps on a fresh VM
- [ ] @whentojump walk through the steps on a fresh VM
- [x] Add a line on how reviewers would get the CloudLab account from the organizer

**Comment by tianyin** [comment]
@marshtompsxd please append more when you see things

**Comment by whentojump** [comment]
Regarding:

> Move data to submodule. Now the tests are failing due to No space left on device

I'm not sure whether reverting the huge blob can be a long-term solution. We probably need a rebase and force push. But if the action is functioning again we can postpone this job.

**Comment by tylergu** [comment]
Yeah I just deleted the huge blob as another commit because I don't want to force push

**Comment by whentojump** [comment]
I actually meant, even we did delete them they are still in the history and make this repository large.
But again if the action is now good, we can be less concerned at this moment.

**Comment by tylergu** [comment]
Yes I know, I think cloning the repo would be slower than before.
But I think the CI fetches the repo without history
