### ISSUE TITLE
Add docs to interpret the output

### ISSUE THREAD

**Issue by tianyin** [xlab-uiuc/acto#267]
From @tylergu 

> Reviewer A, E suggests adding the explanation for the files produced by Acto to the documentation. -- We do have this information in the documentation, but the format of the files are frequently changed, and the current one is not up to date: https://github.com/xlab-uiuc/acto/blob/main/docs/development.md

@tylergu I know the changes from @KashunCheng / @Spedoske changed the format a bit. So we need a different one for the master branch. Can we do both (so we can also make our artifact more interpretable)?

**Comment by tylergu** [comment]
Closed via 8d137f0c65e9e028cbddc7e0cb611467107b2a86
