### ISSUE TITLE
Testing operators to engage with the community from the KubeCon

### ISSUE THREAD

**Issue by tylergu** [xlab-uiuc/acto#278]
At KubeCon, several folks expressed interest in our tool and asked us to test their operators:
- [ ] https://github.com/Altinity/clickhouse-operator
- [ ] https://kubeblocks.io/
- [ ] https://github.com/cloudnative-pg/cloudnative-pg

**Comment by tianyin** [comment]
@tylergu Can you break it into three issues rather than one?
