### ISSUE TITLE
Reproducing Kubernetes Bug 59848 using Acto

### ISSUE THREAD

**Issue by kapilagrawal95** [xlab-uiuc/acto#314]
Hi, is it possible to reproduce this bug (https://github.com/kubernetes/kubernetes/issues/59848) using acto?

**Comment by marshtompsxd** [comment]
Hi @kapilagrawal95 , thanks for your interest in Acto. We are integrating some fault injection features into Acto but at this stage Acto is not ready to reproduce the stale read issues you referred to.
To trigger this type of failures, you can refer to Sieve.
Paper: https://www.usenix.org/system/files/osdi22-sun.pdf
Code: https://github.com/sieve-project/sieve (see the stale-state testing pattern)

**Comment by marshtompsxd** [comment]
Sieve finds (and can reproduce) bugs in k8s controllers caused by the stale read pattern described in https://github.com/kubernetes/kubernetes/issues/59848, but we didn't use Sieve to reproduce the exact issue described in https://github.com/kubernetes/kubernetes/issues/59848; Reproducing that described issue requires fault injection to kubelet, which Sieve does not support yet.

**Comment by tianyin** [comment]
@kapilagrawal95 Would you be able to talk more about your use cases regarding the specific bug you'd like to reproduce? Are you trying to do some research project (if that's the case, Sieve has plenty similar bugs). Or you want to test certain specific Kubernetes components (we planned a few new features on top of Sieve and Acto ahead and we can see how things align)?

**Comment by kapilagrawal95** [comment]
Hi Prof. @tianyin : My use-case is pretty similar to this open issue (https://github.com/sieve-project/sieve/issues/43) on running multiple replicas of the controller (such as 2 kube-schedulers running across separate geographies) to see if we hit race conditions that violate safety/liveness issues. More broadly, my research is focussed into understanding how can kubernetes control plane be extended in a multi-cloud setting spread across different locations with flaky network conditions. Some questions that I am exploring are: do we need strong consistency guarantees for all controllers (such as HPA, Namespace-controller, etc)to run or can we make-do with weaker consistency guarantees? (Our assumption is for those controllers where we require only local state, we should be able to run but where global state is required then stronger consistency will be needed.) Next, we want to explore what are some alternatives for controllers which require strong consistency and how can we relax them? Also some of our research is inspired by Marc Brooker's blog which talks about the risks of when multiple clusters are coordinating (https://brooker.co.za/blog/2019/05/01/emergent.html) and how the dynamics of this is little explored.

**Comment by tianyin** [comment]
I see. Thank you for the explanation! 

yes we haven't built the multi-controller support yet tho it's an important task on our list. The problems you are working on is very cool. 

The k8s bug you referred to, which is essentially a stale-read issue, is not supported by the current implementation of Sieve. But, there are plenty of stale-read bugs Sieve found which in principle have the same pattern: 
https://github.com/sieve-project/sieve/blob/main/docs/bugs.md
(search "stale state")

I'm not sure whether those can help with your research.

**Comment by kapilagrawal95** [comment]
Thanks! I am closing this issue.
