### ISSUE TITLE
Failed to execute the system commands will cause a CRITICAL error and make one thread exit

### ISSUE THREAD

**Issue by qsdrqs** [xlab-uiuc/acto#329]
Hi, I'm currently working on porting Acto to [zalando_postgres-operator](https://github.com/zalando/postgres-operator). In some rare cases, `kind delete` or other system commands may fail to execute after running for several hours on a thread, which will cause a CRITICAL error and make this thread exit.

Specifically in my case, my `Thread-1` tried to execute a \[‘kind’, ‘delete’, ‘cluster’, ‘–name’, ‘acto-0-cluster-0’, ‘–kubeconfig’, ‘/root/.kube/kind-acto-0-cluster-0’\] command after testing for 2 hours, but the `kind` command occasionally failed (maybe because of some bugs in kind or docker but it’s hard to reproduce). I got the following output in stderr:

```

Deleting cluster “acto-0-cluster-0” …  
ERROR: failed to delete cluster “acto-0-cluster-0”: failed to delete nodes: command “docker rm -f -v acto-0-cluster-0-worker3 acto-0-cluster-0-worker2 acto-0-cluster-0-worker acto-0-cluster-0-control-plane” failed with error: exit status 1  
Command Output: acto-0-cluster-0-worker3  
acto-0-cluster-0-worker2  
acto-0-cluster-0-worker  
Error response from daemon: Could not kill running container 7a94fcc7842359a3ea5cfffe729860fa7688dad8a24f7f7a793b38e10a6365be, cannot remove - tried to kill container, but did not receive an exit event
```

and corresponding log in `test.log`:

```

2024-02-23 19:08:43,231 CRITICAL, Thread-1 (run), error_handler.py:79, [trial: 11, gen: 3] An exception occured: <class 'subprocess.CalledProcessError'>: Command '['kind', 'delete', 'cluster', '--name', 'acto-0-cluster-0', '--kubeconfig', '/root/.kube/kind-acto-0-cluster-0']' returned non-zero exit status 1..
```

As this is a CRITICAL error in Acto and the Thread-1 will exit and abort the remaining tests, but it’s more like an error from docker or kind. I’m wondering if it would be better if Acto could try again for several times (maybe 5 times) on the same command if that failed for the first time, instead of just reporting CRITICAL and exiting the thread at the first failing?

-----------------

I'm happy to create a PR to help it and will work on this soon.

**Comment by tianyin** [comment]
Thanks a lot for reporting the problem @qsdrqs ! It's a great analysis!

If you could create a PR, it will be extremely appreciated.

**Comment by tylergu** [comment]
Thank you for reporting this problem @qsdrqs ! Yeah I think having a retry mechanism for Acto in this case would be great!
