### ISSUE TITLE
Acto hang if fail to deploying operator in learning phase

### ISSUE THREAD

**Issue by TwinIsland** [xlab-uiuc/acto#335]
If user makes a mistake in their `apply` field (the field that teach actor how to deploy their operator), and fianlly leads to an unsuccessful deployment, Acto will hang indefinitely ([I've encounter this problem in practice](https://piazza.com/class/lrgyb01xp5q10t/post/99)). This issue arises because the while loop never break if `deploy_with_retry()` does not return True. I am thinking removing the while loop that surrounds `deploy_with_retry()`, as this function is already designed to handle deployment retries effectively. If the operator fails to deploy after retrying, the actor should log the error and exit.

![image](https://github.com/xlab-uiuc/acto/assets/66999583/0b6acb2c-5a17-48b3-a377-6c8c6edcbed8)
https://github.com/xlab-uiuc/acto/blob/53aa9e631f34c8545b138ea1092de58f7504e64b/acto/deploy.py#L125C1-L138C1

![image](https://github.com/xlab-uiuc/acto/assets/66999583/7ce1f369-ddce-4e27-823e-20394d7b8b74)
https://github.com/xlab-uiuc/acto/blob/53aa9e631f34c8545b138ea1092de58f7504e64b/acto/engine.py#L936C1-L954C1

**Comment by TwinIsland** [comment]
sure!

**Comment by tianyin** [comment]
Thank you @TwinIsland ! Looking forward!

**Comment by tylergu** [comment]
Fixed by #339
