### ISSUE TITLE
Duplicate `--context` option when invoking kubectl

### ISSUE THREAD

**Issue by PAN-Ziyue** [xlab-uiuc/acto#351]
**Describe the bug**

This is not really a "bug". `--context` option is added twice when invoking `kubectl`. 

The first one is added at [deploy.py#L85](https://github.com/xlab-uiuc/acto/blob/f2b149d3db9ec5c7152e081284e8109e4a87dc02/acto/deploy.py#L85). 

The second one is added at [kubectl_client/kubectl.py#L39](https://github.com/xlab-uiuc/acto/blob/f2b149d3db9ec5c7152e081284e8109e4a87dc02/acto/kubectl_client/kubectl.py#L39).

**Screenshots**

<img width="858" alt="截屏2024-03-10 11 26 17" src="https://github.com/xlab-uiuc/acto/assets/50222787/6fac53d0-ef62-411e-b42b-0ef55b5b7f15">

**Comment by tianyin** [comment]
@PAN-Ziyue could you send a PR to fix it?

**Comment by tianyin** [comment]
close by #352
